[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = ["fd"]

[source]
command = ["fd -t d --hidden", "fd -t d"]

[preview]
command = "exa -la --color=always '{}'"

[keybindings]
shortcut = "f2"
