# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#89B4FA)\
$username\
[ ](fg:#11111b bg:#89B4FA)\
[](bg:#CDD6F4 fg:#89B4FA)\
$directory\
[](fg:#cdd6f4 bg:#fab387)\
$git_branch\
$git_status\
[](fg:#fab387 bg:#cba6f7)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#cba6f7 bg:#a6e3a1)\
$docker_context\
[](fg:#a6e3a1 bg:#89b4fa)\
$time\
[ ](fg:#89B4FA)\
$line_break$character"""
