[misc]
# am, android_studio, app_man, aqua, asdf, atom, audit, auto_cpufreq, bin, bob,
# brew_cask, brew_formula, bun, bun_packages, cargo, certbot, chezmoi, chocolatey,
# choosenim, cinnamon_spices, clam_av_db, composer, conda, config_update,
# containers, custom_commands, deb_get, den o, distrobox, dkp_pacman, dotnet,
# elan, emacs, firmware, flatpak, flutter, fossil, gcloud, gem, ghcup, git_repos,
# github_cli_extensions, gnome_shell_e xtensions, go, guix, haxelib, helix,
# helm, home_manager, jetbrains_aqua, jetbrains_clion, jetbrains_datagrip,
# jetbrains_dataspell, jetbrains_gateway, jetbrains_goland, jetbrains_idea,
# jetbrains_mps, jetbrains_phpstorm, jetbrains_pycharm, jetbrains_rider,
# jetbrains_rubymine, jetbrains_rustrover, jetb rains_toolbox, jetbrains_webstorm,
# jetpack, julia, juliaup, kakoune, krew, lensfun, lure, macports, mamba, mas,
# maza, micro, microsoft_store, miktex, mise, myrepos, nix, node, opam, pacdef,
# pacstall, pearl, pip3, pip_review, pip_review_local, pipupgrade, pipx, pipxu,
# pixi, pkg, pkgin, platformio_cor e, pnpm, poetry, powershell, protonup, pyenv,
# raco, rcm, remotes, restarts, rtcl, ruby_gems, rustup, rye, scoop, sdkman,
# self_update, sheldon, shell, snap, sparkle, spicetify, stack, stew, system,
# tldr, tlmgr, tmux, toolbx, uv, vagrant, vcpkg, vim, volta_packages, vscode,
# vscodium, waydroid, winget, wsl, wsl_update, xcodes, yadm, yarn, yazi, zigup,
# zvm
disable = ["containers", "git_repos", "helix"]

# ignore_failures = ["powershell"]

# Don't ask for confirmations (no default value)
# assume_yes = true

# Do not ask to retry failed steps (default: false)
# no_retry = true

