## https://raw.githubusercontent.com/atuinsh/atuin/refs/heads/main/crates/atuin-client/config.toml
dialect = "uk"
 
# sync_address = "https://api.atuin.sh"

style = "full"

inline_height = 25  

invert = true 

# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+",
# ]

# cwd_filter = [
#   "^/very/secret/area",
# ]

enter_accept = true

keymap_mode = "vim-insert" # "auto", "vim-normal", "vim-insert", "emacs"


[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
# common_subcommands = [
#   "apt",
#   "cargo",
#   "composer",
#   "dnf",
#   "docker",
#   "git",
#   "go",
#   "ip",
#   "kubectl",
#   "nix",
#   "nmcli",
#   "npm",
#   "pecl",
#   "pnpm",
#   "podman",
#   "port",
#   "systemctl",
#   "tmux",
#   "yarn",
# ]

## Set commands that should be totally stripped and ignored from stats
# common_prefix = ["sudo"]

## Set commands that will be completely ignored from stats
ignored_commands = [
  "cd",
  "ls",
  "vi",
  "hx",
  "omm",
  "yazi",
  "y",
  "z",
  "uv",
  "paru",
  "pacman",
  "let"
]

[sync]
records = true


[daemon]
enabled = true

[theme]
name = "marine" # autumn | marine 

