file_types = ["markdown"]
default_extension = "md"
theme = "default_dark"
vault_path = "~/syncthing/Notes2"
stats_show = "Both"
view_raw = true
viewer = [
    "glow",
    "%p",
]
enable_html = true
css = "default_dark"
katex = true

[math_replacements]
'\field' = '\mathbb'
