"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Zenno Zenith"
email = "95485961+ZennoZenith@users.noreply.github.com"

[signing]
behavior = "own"
backend = "gpg"
# key = "signing@example.com"
key = "7D9AF1B2C19131AD"

[ui]
pager = "delta -s"
diff-formatter = ":git"
